version: '3'
services:
  integration:
    build:
      context: ./integration

  # User Subsystem
  user_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  user_redis:
    image: redis:alpine
  user:
    build:
      context: ./user
    depends_on:
      - user_db
      - user_redis
    #command: rake db:migrate
  
  # API Services Gateway
  gateway:
    image: nginx:stable
    volumes: 
      - ./gateway/nginx:/etc/nginx
    ports:
      - 8080:80
    depends_on:
      - integration
      - user
