version: '3'
services:
  # API Services Gateway
  gateway:
    image: nginx:stable
    volumes: 
      - ./gateway/nginx:/etc/nginx
    ports:
      - 8080:80
    depends_on:
      - integration

  # Mesh up
  integration:
    build:
      context: ./integration
    depends_on:
      - user
      - payment
      - comment
      - inventory
      - cart
      - order
    environment: 
      - USER_SERVICE=http://user:9000
      - COMMENT_SERVICE=http://comment:9001
      - PAYMENT_SERVICE=http://payment:9002
      - INVENTORY_SERVICE=http://inventory:9003
      - ORDER_SERVICE=http://order:9004
      - CART_SERVICE=http://cart:9005
    #ports:
    #  - 8233:8233

  # User Subsystem
  user_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    ports: 
      - 15432:5432
  user_redis:
    image: redis:alpine
  user:
    build:
      context: ./user
    depends_on:
      - user_db
      - user_redis
    #command: "rake db:migrate"

  # Payment Subsystem
  payment_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/payment_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  payment:
    build:
      context: ./payment
    depends_on:
      - payment_db
    #command: "rake db:migrate"

  # Comment Subsystem
  comment_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/comment_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  comment:
    build:
      context: ./comment
    depends_on:
      - comment_db
    #command: "rake db:migrate"

  # Inventory Subsystem
  inventory_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/inventory_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_inventory
  inventory:
    build:
      context: ./inventory
    depends_on:
      - inventory_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory_db:5432/db_inventory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9003

  # Order Subsystem
  order_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/order_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_order
  order:
    build:
      context: ./order
    depends_on:
      - order_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9004
  # cart Subsystem
  cart_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/cart_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_cart
  cart:
    build:
      context: ./cart
    depends_on:
      - cart_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://cart_db:5432/db_cart
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9005
