version: '3'
services:
  integration:
    build:
      context: ./integration

  # User Subsystem
  user_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/user_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  user_redis:
    image: redis:alpine
  user:
    build:
      context: ./user
    depends_on:
      - user_db
      - user_redis
    #command: "rake db:migrate"

  # Payment Subsystem
  payment_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/payment_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  payment:
    build:
      context: ./payment
    depends_on:
      - payment_db
    #command: "rake db:migrate"

  # Comment Subsystem
  comment_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/comment_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
  comment:
    build:
      context: ./comment
    depends_on:
      - comment_db
    #command: "rake db:migrate"

  # Inventory Subsystem
  inventory_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/inventory_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_inventory
  inventory:
    build:
      context: ./inventory
    depends_on:
      - inventory_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://inventory_db:5432/db_inventory
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9003

  # Order Subsystem
  order_db:
    image: postgres:alpine
    volumes:
      - ./.persistence/order_db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: db_order
  order:
    build:
      context: ./order
    depends_on:
      - order_db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://order_db:5432/db_order
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SERVER_PORT: 9004
  # API Services Gateway
  gateway:
    image: nginx:stable
    volumes: 
      - ./gateway/nginx:/etc/nginx
    ports:
      - 8080:80
    depends_on:
      - integration
      - user
